import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from 'next/link'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

<div className="bg-gray-400 text-gray-900 flex justify-between items-center min-h-12">
  <div className="ml-48">
    <Link href="/." className="text-lg font-bold"> Zahid </Link>
  </div>

  <div className="flex space-x-4 mr-56">
    <Link href="/." className="text-lg"> Home </Link>
    <Link href="/about" className="text-lg"> About Me </Link>
    <Link href="/skill" className="text-lg"> Skill </Link>
    <Link href="/experience" className="text-lg"> Experience </Link>
    <Link href="/service" className="text-lg"> Service </Link>
    <Link href="/project" className="text-lg"> Project & Research </Link>
    <Link href="/contact" className="text-lg"> Contact </Link>
  </div>
</div>


        {children}
      </body>
    </html>
  );
}
