import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-gray-400 text-gray-900 h-12 flex pr-48 justify-end items-center">
        <Link href="/." className="ml-4"> Home </Link>
        <Link href="/about" className="ml-4"> About Me </Link>
        <Link href="/skill" className="ml-4"> Skill </Link>
        <Link href="/experience" className="ml-4"> Experience </Link>
        <Link href="/service" className="ml-4"> Service </Link>
        <Link href="/project" className="ml-4"> Project & research</Link>
        <Link href="/contact" className="ml-4"> Contact </Link>
        </div>









        {children}
      </body>
    </html>
  );
}
